wandb_version: 1

augmentations_enabled:
  value: true
model.name:
  value: resnet18
optimizer.learning_rate:
  value: 0.001
optimizer.momentum:
  value: 0.9
optimizer.nesterov:
  value: true
optimizer.type:
  value: SGD
optimizer.weight_decay:
  value: 0.001
scheduler.gamma:
  value: 0.1
scheduler.patience:
  value: 5
scheduler.step_size:
  value: 10
scheduler.type:
  value: ReduceLROnPlateau
