# config/default_config.yaml

dataset:
  name: "CIFAR100"
  batch_size: 256
  cache: true
  augmentations:
    random_flip: true
    random_crop: true
    random_rotation: true
    color_jitter: true
    normalization: true
  other_augmentations:
    enabled: true

model:
  name: "resnet18"
  num_classes: 100
  pretrained: true

optimizer:
  type: "Adam"
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: true

scheduler:
  type: "CosineAnnealingLR"
  step_size: 5
  gamma: 0.1
  patience: 5
  T_max: 50

training:
  epochs: 50
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 0.01

sweep:
  enabled: false
  method: "grid"
  metric:
    name: "Validation Accuracy"
    goal: "maximize"
  parameters:

    training.epochs:
      values: [ 50 ]
    training.early_stopping.enabled:
      values: [ true ]
    training.early_stopping.patience:
      values: [ 3 ]
    training.early_stopping.min_delta:
      values: [ 0.01 ]

    dataset.name:
      values: [ CIFAR100 ]
    dataset.batch_size:
      values: [ 256 ]
    dataset.cache:
      values: [ true ]

    model.name:
      values: [ "resnet18", "preact_resnet18" ]
    model.pretrained:
      values: [ true ]
    augmentations_enabled:
      values: [ true ]
    other_augmentations_enabled:
      values: [ false , true ]

    optimizer.type:
      values: [ "SGD", "Adam" ]
    optimizer.learning_rate:
      values: [ 0.0001, 0.01 ]
    optimizer.weight_decay:
      values: [ 0.001 ]
    optimizer.momentum:
      values: [ 0.9 ]
    optimizer.nesterov:
      values: [ true ]

    scheduler.type:
      values: [ "ReduceLROnPlateau" , "CosineAnnealingLR" ]
    scheduler.step_size:
      values: [ 10 ]
    scheduler.gamma:
      values: [ 0.1 ]
    scheduler.patience:
      values: [ 5 ]
    scheduler.T_max:
      values: [ 50 ]
