_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
                - 49
                - 51
                - 55
                - 63
                - 105
            "2":
                - 1
                - 2
                - 3
                - 41
                - 49
                - 51
                - 55
                - 63
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
dataset:
    value:
        augmentations:
            color_jitter: true
            dataset: CIFAR100
            random_crop: true
            random_flip: true
            random_rotation: true
        batch_size: 256
        cache: true
        name: CIFAR100
model:
    value:
        name: resnet18
        num_classes: 100
        pretrained: true
optimizer:
    value:
        learning_rate: 0.01
        momentum: 0.9
        nesterov: true
        type: SGD
        weight_decay: 0.0001
scheduler:
    value:
        gamma: 0.1
        patience: 5
        step_size: 10
        type: ReduceLROnPlateau
sweep:
    value:
        enabled: false
        method: grid
        metric:
            goal: maximize
            name: Validation Accuracy
        parameters:
            augmentations_enabled:
                values:
                    - true
                    - false
            learning_rate:
                values:
                    - 0.001
                    - 0.01
            model_name:
                values:
                    - resnet18
                    - preact_resnet18
            momentum:
                values:
                    - 0.9
            nesterov:
                values:
                    - true
            optimizer_type:
                values:
                    - SGD
                    - Adam
            weight_decay:
                values:
                    - 0.0001
training:
    value:
        early_stopping:
            enabled: true
            min_delta: 0.01
            patience: 3
        epochs: 1
